#!/bin/bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

echo "+++ :github: Opening Pull Request"

if [[ -z "${GITHUB_TOKEN:-}" ]]; then
  echo 'Error: GITHUB_TOKEN environment variable not set'
  echo 'A Github personal access token with repo permissions is needed to open pull requests'
  exit 1
fi

base=$(plugin_read_config BASE master)
body=$(plugin_read_config BODY '')
head=$(plugin_read_config HEAD "${BUILDKITE_BRANCH}")
title=$(plugin_read_config TITLE '')
repo=$(plugin_read_config REPO "$(repo_from_origin)")

open_pull_request "$title" "$body" "$head" "$base" "$repo"
response=$(cat "tmp/github_api_calls/open_pull_request_response.json")
pr_number=$(echo "$response" | jq '.number')
html_url=$(echo "$response" | jq '.html_url')
echo "Github pull request opened: ${html_url}"

reviewers=$(plugin_read_list REVIEWERS)
team_reviewers=$(plugin_read_list TEAM_REVIEWERS)
if [[ -n "${reviewers:-}" || "${team_reviewers:-}" ]]; then
  request_reviews "$reviewers" "$team_reviewers" "$pr_number" "$repo"
  echo 'Reviews requested'
fi

labels=$(plugin_read_list LABELS)
if [[ -n "${labels:-}" ]]; then
  add_labels "$labels" "$pr_number" "$repo"
  echo 'Labels added'
fi
