#!/bin/bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

echo
echo "+++ :github: Opening Pull Request"
echo

base=$(plugin_read_config BASE master)
body=$(plugin_read_config BODY '')
head=$(plugin_read_config HEAD "${BUILDKITE_BRANCH}")
title=$(plugin_read_config TITLE '')
repo=$(plugin_read_config REPO "$(repo_from_origin)")

echo "Opening pull request"
response=$(open_pull_request "$title" "$body" "$head" "$base" "$repo")
pr_number=$(echo "$response" | jq '.number')

reviewers=$(plugin_read_list REVIEWERS)
team_reviewers=$(plugin_read_list TEAM_REVIEWERS)
if [[ -n "${reviewers:-}" || "${team_reviewers:-}" ]]; then
  echo "Adding reviewers"
  request_reviews "$reviewers" "$team_reviewers" "$pr_number" "$repo"
fi

labels=$(plugin_read_list LABELS)
if [[ -n "${labels:-}" ]]; then
  echo "Adding labels"
  add_labels "$labels" "$pr_number" "$repo"
fi

url=$(echo "$response" | jq '.html_url')
echo
echo "Github Pull request opened: ${url}"
